// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmvwpylpvmvqliirlyhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtdndweWxwdm12cWxpaXJseWhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NDU4MDksImV4cCI6MjA3MDAyMTgwOX0.3f0LxWrn0_HvP58koaP0wMSIGn3-6kmWuQpRyGLaU8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});